### ISSUE TITLE
Issues with JBR SDK

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej-launcher#75]
Please leave screenshots with a note on the operating system used

**Comment by elevans** [comment]
**Operating System**: Ubuntu 20.04.1 LTS 64-bit

Menu options do not render after initial start:
![fiji_missing_menus](https://user-images.githubusercontent.com/6422847/95356398-3b674780-088c-11eb-9608-3d06868ce86d.png)

They appear after clicking anywhere on the menu bar:
![fiji_menu_interact](https://user-images.githubusercontent.com/6422847/95356825-b7618f80-088c-11eb-8e29-c1d31d79c738.png)

This seems to be present everywhere. Here I tried to pick different LUTs:
![fiji_luts](https://user-images.githubusercontent.com/6422847/95356976-e4ae3d80-088c-11eb-821c-c5b93912f628.png)

**Comment by ctrueden** [comment]
On macOS, noticed two problems right away:

* `Contents/MacOS/Imagej-macosx` needs to be named `Contents/MacOS/ImageJ-macosx`.
* That file needs to have the executable bit set, but does not.

Similarly, though it doesn't affect macOS, the other platforms' native launchers are similarly misnamed.

**Comment by ctrueden** [comment]
With the JBRSDK8 bundle, FLIMJ's JavaFX UI starts up successfully on macOS, but then hangs when I click the "Fit dataset" button. This may not be a JBRSDK8-specific issue; I'll investigate further when I have time.

**Comment by hinerm** [comment]
> On macOS, noticed two problems right away:
> 
>     * `Contents/MacOS/Imagej-macosx` needs to be named `Contents/MacOS/ImageJ-macosx`.
> 
>     * That file needs to have the executable bit set, but does not.
> 
> 
> Similarly, though it doesn't affect macOS, the other platforms' native launchers are similarly misnamed.

@ctrueden yeah this didn't affect windows and the updater tracked the files appropriately. I'm sure this is because I manually downloaded the `imagej-launcher` resources from Maven and renamed them. The `fiji-builds` bundles will be correct I'm sure.
 
> After fixing these issues, I'm able to start Fiji via the usual right-click, Open, click Open to pass through the "Unidentified developer" warning dialog, and then Fiji works. 👍

This is interesting because @tpietzsch mentioned the [Unidentified developer warning was gone](https://gitter.im/fiji/DevOps?at=5f758e491bb53378fea90769) for him

**Comment by ctrueden** [comment]
With JBRSDK11 on macOS, three problems so far:

1. The executable bit of `Contents/MacOS/ImageJ-macosx` is not set.
2. The search bar is not sized correctly; see screenshots below.
3. FLIMJ does not work—see stack trace below. Does JBRSDK11 ship with OpenJFX11? If not, we may need to start shipping OpenJFX11 JARs on the FLIMJ update site (which would bump FLIMJ's minimum required Java version to 11).

<details><summary>FLIMJ stack trace</summary>

```
[INFO] Reading SDT header
Warning: Nashorn engine is planned to be removed from a future JDK release
Oct 07, 2020 3:56:39 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 11.0.1 by JavaFX runtime of version 10.0.2-internal
Warning: Nashorn engine is planned to be removed from a future JDK release
Oct 07, 2020 3:56:39 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 11.0.1 by JavaFX runtime of version 10.0.2-internal
Warning: Nashorn engine is planned to be removed from a future JDK release
Oct 07, 2020 3:56:39 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 11.0.1 by JavaFX runtime of version 10.0.2-internal
Oct 07, 2020 3:56:40 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 11.0.1 by JavaFX runtime of version 10.0.2-internal
Oct 07, 2020 3:56:40 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 11.0.1 by JavaFX runtime of version 10.0.2-internal
Oct 07, 2020 3:56:40 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 11.0.1 by JavaFX runtime of version 10.0.2-internal
Exception in thread "JavaFX Application Thread" [WARNING] FLIMJ: UI init failed or aborted by user. Exiting.
java.lang.NoClassDefFoundError: com/sun/javafx/scene/control/skin/BehaviorSkinBase
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.controlsfx.control.SegmentedButton.createDefaultSkin(SegmentedButton.java:195)
	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:897)
	at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
	at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:900)
	at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
	at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:900)
	at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
	at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:900)
	at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
	at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:900)
	at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
	at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9515)
	at javafx.graphics/javafx.scene.Scene.doCSSPass(Scene.java:583)
	at javafx.graphics/javafx.scene.Scene.preferredSize(Scene.java:1770)
	at javafx.graphics/javafx.scene.Scene$2.preferredSize(Scene.java:394)
	at javafx.graphics/com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66)
	at javafx.graphics/javafx.stage.Window$12.invalidated(Window.java:1098)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.graphics/javafx.stage.Window.setShowing(Window.java:1186)
	at javafx.graphics/javafx.stage.Window.show(Window.java:1201)
	at javafx.graphics/com.sun.javafx.stage.EmbeddedWindow.show(EmbeddedWindow.java:71)
	at javafx.swing/javafx.embed.swing.JFXPanel.setSceneImpl(JFXPanel.java:328)
	at javafx.swing/javafx.embed.swing.JFXPanel.setScene(JFXPanel.java:298)
	at flimlib.flimj.ui.FLIMJCommand.initFX(FLIMJCommand.java:129)
	at flimlib.flimj.ui.FLIMJCommand.lambda$run$0(FLIMJCommand.java:57)
	at flimlib.flimj.ui.FLIMJCommand.lambda$runAndWait$2(FLIMJCommand.java:96)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.scene.control.skin.BehaviorSkinBase
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 135 more
Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: com/sun/javafx/scene/control/skin/BehaviorSkinBase
	at org.controlsfx.control.SegmentedButton.createDefaultSkin(SegmentedButton.java:195)
	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:897)
	at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
	at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:886)
	at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
	at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:886)
	at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
	at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:886)
	at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
	at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:886)
	at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
	at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9515)
	at javafx.graphics/javafx.scene.Scene.doCSSPass(Scene.java:583)
	at javafx.graphics/javafx.scene.Scene.access$3500(Scene.java:173)
	at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2502)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:410)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:409)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:436)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:524)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:504)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:497)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:320)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
```

</details>

### Search bar screenshots

Search bar window packs incorrectly:

<img width="695" alt="search-bar-too-small" src="https://user-images.githubusercontent.com/556626/95395398-1db5d480-08c4-11eb-9818-2a63e77af44b.png">

Even after sizing it up, the layout is incorrect (missing left-hand list pane):

<img width="678" alt="search-bar-layout-wrong" src="https://user-images.githubusercontent.com/556626/95395405-23abb580-08c4-11eb-9bd9-aef3c4fba699.png">

The "Embed search results in main window" option can be enabled as a workaround:

<img width="721" alt="search-bar-workaround" src="https://user-images.githubusercontent.com/556626/95395412-27d7d300-08c4-11eb-85ab-b78bd4f23291.png">

**Comment by ctrueden** [comment]
> @tpietzsch mentioned the Unidentified developer warning was gone for him

I would be shocked if that warning ever disappears without us paying $99 to Apple and signing the app.

@tpietzsch Might you have disabled Gatekeeper (`sudo spctl --master-disable`) and enabled apps to run from anywhere, as described e.g. [here](https://www.imore.com/how-open-apps-anywhere-macos-catalina-and-mojave)?

**Comment by tpietzsch** [comment]
No, I didn't. I have these security settings:
![Screenshot 2020-10-08 at 15 45 08](https://user-images.githubusercontent.com/622070/95467099-59f93b80-097d-11eb-9f4b-9263ed3f3d48.png)

Also there is a new splash screen, that I didn't notice before:
![Screenshot 2020-10-08 at 15 48 25](https://user-images.githubusercontent.com/622070/95467702-105d2080-097e-11eb-8731-911c4edf848e.png)

I thought the two might be related and there is a new launcher or something...

**Comment by ctrueden** [comment]
We determined that JBRSDK11 ships with JavaFX10, which does not play nicely with ControlsFX 8. We tried ControlsFX 9, as well as ControlsFX 11, but neither works correctly with FLIMJ. There are issues with the FLIMJ UI freezing on fit with both JBRSDK8 and JBRSDK11.

We tested AdoptOpenJDK11 with JavaFX11 libraries in `jars/` and that works (on macOS). So it's looking likely we won't be able to use the JBRSDK after all—almost certainly not JBRSDK11, which ships a probably-unworkable embedded JavaFX version. But JBRSDK8 is also looking less likely due to the FLIMJ deadlock issue.

The downside of shipping AdoptOpenJDK11 with JavaFX11 libraries is that anyone who wants to keep using Java 8 won't be able to use JavaFX-based functionality anymore. Current line of thinking is to create new ImageJ-11 and Fiji-11 update sites that ship Java-11-friendly artifacts, which would include the JavaFX11 libraries. We could then finally retire the Java-8 update site, and once again provide a vanilla ImageJ2 download again! 🎉  But we need further thought, input, and testing before we're sure this approach will really work.

**Comment by hinerm** [comment]
@elevans Would you mind testing one more time [with our new Zulu bundle for linux](https://downloads.imagej.net/test/launcher/Fiji-zulujdk8-jfx.tar.gz)? It's a different JDK 8 and we're hoping it doesn't have the same menu bar issues any more.

Thank you!

**Comment by elevans** [comment]
@hinerm you got it! And I'm happy to test as many times as needed! Will report back.

**Comment by elevans** [comment]
@hinerm Tried it out and its working fine on my system. Menu bar issues are no longer present with this bundle.

**Comment by hinerm** [comment]
The latest launcher has been released, and all downloads [have been updated](https://travis-ci.com/github/fiji/fiji-builds/builds/198246882) to Azul Java 8 JDK+FX

**Comment by ctrueden** [comment]
I tried to download the JBR SDK 8 today, and I can't find the downloads anymore. JetBrains moved things around, and only offers downloads of 11 and 17 now. We'll be moving to 11 or 17 anyway ASAP, but just wanted to note that here.
